Added C++ elastic lib
Gold872/elastic-dashboard pull request #109
Opened 2024-10-07 11:32 UTC by DanPeled

Might be a good idea to use JNI with the java version if it is planned to move this into a vendordep

- Take in care that the path for the include in`elasticlib.cpp` might need to be modified to match the actual path in the project of `elasticlib.h`

2024-10-07 13:16 UTC, spacey-sooty commented on elasticlib/C++/include/Elastic.h
> +    struct ElasticNotification {
This doesn't need to be nested in C++

2024-10-07 13:16 UTC, spacey-sooty commented on elasticlib/C++/include/Elastic.h
> +        enum class NotificationLevel {
ditto

2024-10-07 13:17 UTC, spacey-sooty commented on elasticlib/C++/include/Elastic.h
> +nt::StringPublisher Elastic::publisher = Elastic::topic.Publish(nt::PubSubOption::SendAll(true), nt::PubSubOption::KeepDuplicates(true));
top of file instead

2024-10-14 02:54 UTC, Cynosure-null commented
Hi, I've been trying to use this for my team and I've been running into the error `fatal error: networktables/StringPublisher.h: No such file or directory`. on line 6 What WPILib version does this work on? Thanks for your work on this.

2024-10-14 03:51 UTC, spacey-sooty requested changes

2024-10-14 03:51 UTC, spacey-sooty commented on elasticlib/C++/include/Elastic.h
> +#include <networktables/StringPublisher.h>
```suggestion
```

2024-10-14 03:51 UTC, spacey-sooty commented
> Hi, I've been trying to use this for my team and I've been running into the error `fatal error: networktables/StringPublisher.h: No such file or directory`. on line 6 What WPILib version does this work on? Thanks for your work on this.

StringPublisher.h doesn't exist. If you remove it this should work

2024-10-14 04:27 UTC, Cynosure-null commented
I don't have write access to this pr, but line 12 should be `        nt::StringPublisher publisher = topic.Publish({.sendAll = true, .keepDuplicates = true});` to prevent issues about not finding the `nt::PubSubOptions` class

2024-10-14 04:42 UTC, DanPeled commented
I'll see what I did wrong when I get the chance, probably will get it done by the end of the day

2024-11-15 15:42 UTC, DanPeled commented
Depends on #133

2024-11-16 17:49 UTC, merged