Make elasticlib C++ library more idiomatic
Gold872/elastic-dashboard pull request #140
Opened 2024-11-23 22:01 UTC by calcmogul

* Flatten the type structure
* Put all classes and functions in an elastic namespace
* Rename the Notification class to Alert to match the user-facing function
* Since the Alert class provides setters and getters, just make the members public to allow aggregate initialization
* Remove redundant Javadoc tags from comments
* Rewrite the Javadoc-like comments to follow Doxygen conventions
* Make pixel counts use ints, since them being fractional makes no sense
* Move the JSON serialization and NT publishing to a .cpp file

2024-11-23 22:09 UTC, calcmogul commented
I can port this to Java as well in this PR if the changes are good.

2024-12-09 16:05 UTC, Gold872 requested changes
I'm a big fan of these changes, however I want to rename `Alert` and `AlertLevel` to `Notification` and `NotificationLevel` to avoid confusion with the WPILib Alerts API

Besides that though this looks great!

2024-12-09 16:05 UTC, Gold872 commented on elasticlib/Elastic.java
> +  public static class Alert {
I prefer keeping this as ElasticNotification or Notification to avoid it getting confused with WPILib Alerts, since these serve a different purpose

2024-12-09 16:05 UTC, Gold872 commented on elasticlib/Elastic.java
> +    public lert(
should be changed to `public Alert(`

2024-12-09 19:12 UTC, Gold872 commented on elasticlib/elasticlib.py
What's the reason for removing the method chaining api?

2024-12-09 19:23 UTC, calcmogul commented on elasticlib/elasticlib.py
It's not idiomatic Python.

2024-12-14 17:58 UTC, Gold872 commented on elasticlib/elasticlib.py
Since I'm not fully familiar with the python OOP features, what exactly would this look like? I'm rewriting some of the code examples

2024-12-14 18:15 UTC, calcmogul commented on elasticlib/elasticlib.py
```py
send_notification(Notification(level=NotificationLevel.INFO, description="Hello World!")
```

2024-12-14 18:57 UTC, Gold872 commented on elasticlib/elasticlib.py
In terms of method chaining, is that type of functionality a thing in python or would they have to update all of the properties one at a time?

2024-12-14 19:44 UTC, calcmogul commented on elasticlib/elasticlib.py
You _could_ reuse a notification object and update the public properties after construction, but I don't see why you'd want to. That's more typing than just making a new notification.

2024-12-14 19:50 UTC, Gold872 approved these changes

2024-12-14 20:04 UTC, merged